# -*- mode: ruby -*-
# vi: set ft=ruby :

ip_gl = "192.168.33.10"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.define "gitlab"
  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: ip_gl
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2560"
  end
  config.vm.provision "shell", inline: <<-SHELL   
    sudo apt-get update
    sudo apt-get install -y curl openssh-server ca-certificates
    curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
    sudo EXTERNAL_URL=$ip_gl apt-get install gitlab-ce
    export LC_CTYPE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    sudo dpkg-reconfigure locales
    sudo gitlab-ctl reconfigure
  SHELL
end
